[package]
name = "surreal-s3"
version = "0.1.0"
edition = "2024"
license = "BSD-3-Clause"
repository = "https://github.com/yuunalein/surreal-s3"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1"
aws-config = { version = ">=1.12, <2.0.0", features = [
    "rt-tokio",
], default-features = false }
aws-sdk-s3 = { version = ">=1.146, <2.0.0", default-features = false }
aws-smithy-runtime-api = { version = "1.16", default-features = false, features = [
    "client",
    "http-1x",
] }
aws-smithy-types = { version = "1.6", default-features = false, features = [
    "http-body-1-x",
] }
bytes = "1"
chrono = "0.4"
hickory-resolver = ">=0.26, <1.0.0"
http = ">=1.5, <2.0.0"
http-body-util = "0.1"
hyper = { version = ">=1.11, <2.0.0", default-features = false, features = [
    "client",
    "http1",
    "http2",
] }
hyper-util = { version = "0.1", default-features = false, features = ["tokio"] }
rustls = { version = ">=0.23, <1.0.0", default-features = false, features = [
    "ring",
    "std",
    "tls12",
] }
surrealism = "0.5.0"
surrealdb-types = "3.2.4"
tokio = { version = "1", default-features = false, features = [
    "io-util",
    "net",
    "rt",
    "sync",
    "time",
] }
tokio-rustls = { version = ">=0.26, <1.0.0", default-features = false }
tokio-util = { version = "0.7", features = ["io-util"] }
webpki-roots = "1"
