name: CI

on:
  push:
    branches: [main]
    paths-ignore:
      - 'docs/**'
  pull_request:
    paths-ignore:
      - 'docs/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          targets: wasm32-wasip2
          components: clippy
      - uses: Swatinem/rust-cache@v2

      - name: Build
        run: cargo build --target wasm32-wasip2 --release

      - name: Clippy
        run: cargo clippy --target wasm32-wasip2 --release -- --no-deps --deny warnings

      - name: Install SurrealDB
        uses: ccorsi/setup-surrealdb@v1
        with:
          version: latest

      - name: Build surreal module
        run: surreal module build --out s3.surli

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: s3.surli
          path: s3.surli
