name: CI

on:
  push:
    branches: [main]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      docs: ${{ steps.filter.outputs.docs }}
      rust: ${{ steps.filter.outputs.rust }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            docs:
              - 'docs/**'
            rust:
              - '!docs/**'

  docs:
    needs: changes
    if: needs.changes.outputs.docs == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        working-directory: docs
        run: bun install --frozen-lockfile

      - name: Build docs
        working-directory: docs
        run: bun run build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: docs/dist

  build:
    needs: changes
    if: needs.changes.outputs.rust == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          targets: wasm32-wasip2
          components: clippy
      - uses: Swatinem/rust-cache@v2

      - name: Build
        run: cargo build --target wasm32-wasip2 --release

      - name: Clippy
        run: cargo clippy --target wasm32-wasip2 --release -- --no-deps --deny warnings

      - name: Install SurrealDB
        uses: ccorsi/setup-surrealdb@v1
        with:
          version: latest

      - name: Build surreal module
        run: surreal module build --out s3.surli

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: s3.surli
          path: s3.surli
